### ISSUE TITLE
Project 2 Requirements Checklist

### ISSUE THREAD

**Issue by SleekWingX** [mpredelus3/Post-Me#7]
- [x] Use Node.js and Express.js to create a RESTful API.
- [x] Use Handlebars.js as the template engine.
- [x] Use PostgreSQL and the Sequelize ORM for the database.
- [x] Have both GET and POST routes for retrieving and adding new data.
- [ ] Use at least one new library, package, or technology that we haven’t discussed.
- [x] Have a folder structure that meets the MVC paradigm.
- [ ] Include authentication (express-session and cookies).
- [x] Protect API keys and sensitive information with environment variables.
- [x] Be deployed using Render (with data).
- [x] Have a polished UI.
- [x] Be responsive.
- [x] Be interactive (in other words, accept and respond to user input).
- [x] Meet good-quality coding standards (file structure, naming conventions, follows best practices for class/id naming conventions, indentation, quality comments, and so on).
- [x] Have a professional README (with unique name, description, technologies used, screenshot, and link to deployed application).
